---
services:
  app:
    build:
      context: .
      args:
        # To use a specific Moodle version, set MOODLE_VERSION to git release tag.
        # You can find the list of available tags at:
        # https://api.github.com/repos/moodle/moodle/tags
        #
        # Example:
        # MOODLE_VERSION: v4.5.3
        # MOODLE_VERSION: main # (disabled because moodle 5.1dev has many changes)
        MOODLE_VERSION: v5.0.1
    environment:
      - SITE_URL=http://app:8080
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=moodle
      - POSTGRES_USER=moodle
      - POSTGRES_DB=moodle

  sut:
    image: alpine:latest
    depends_on:
      - app
    environment:
      - SOURCE_BRANCH
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
